### ISSUE TITLE
Write AavegotchiFacet setPetOperatorForAll

### ISSUE THREAD

**Issue by devism** [mark3labs/louper#10]
The execute button does not seem to do anything. No results are given and the diamond keeps blinking.

**Comment by devism** [comment]
Nevermind. I guess I was using the old version at louper.dev

**Comment by superresistant** [comment]
> Nevermind. I guess I was using the old version at louper.dev

Wait I have the same problem. What's the old and new version of louper.dev ?
How did you solve the problem ?
